# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
create_cfn_infrastructure:
  docker:
    - image: amazon/aws-cli0
  checkout:
  run:
    name: " Creation of infrastructure using cloudformation"
    command: |
      aws cloudformation deploy \
      --template template.yml \
      --stack-name demo_cicd_stack-${CIRCLE_WORKFLOW_ID:0:5} \
      --region us-east-1 
workflows:
  cfn-circleci-workflow:
    jobs:
      - create_cfn_infrastructure
