# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
create_infrastructure: 
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: "echo Hello, World!"

workflows:
  my_workflow:
      jobs:
        - create_infrastructure